import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  turbopack: {
    root: __dirname,
  },
  experimental: {
    optimizePackageImports: [
      "lucide-react",
      "@radix-ui/react-tabs",
      "@radix-ui/react-dialog",
      "@radix-ui/react-select",
      "@radix-ui/react-collapsible",
      "@radix-ui/react-checkbox",
      "@radix-ui/react-toast",
      "@radix-ui/react-slot",
      "@radix-ui/react-avatar",
      "@radix-ui/react-switch",
      "@radix-ui/react-tooltip",
      "@radix-ui/react-accordion",
      "@radix-ui/react-label",
      "@radix-ui/react-popover",
      "@radix-ui/react-slider",
    ],
  },
  async redirects() {
    return [
      // Leistungen Reinigung/Facility: flache Pfade → verschachtelte Silo-Pfade
      { source: "/leistungen/reinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/reinigung/", destination: "/leistungen/reinigung-facility/reinigung/", permanent: true },
      { source: "/leistungen/facility", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/facility/", destination: "/leistungen/reinigung-facility/facility/", permanent: true },
      // Elektrotechnik Thin-Content: gelöschte Unterseiten → Hauptseite
      { source: "/leistungen/elektrotechnik/e-mobility", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/e-mobility/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/hauselektrik", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/hauselektrik/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/klingelanlagen", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/klingelanlagen/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/led", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/led/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/messsysteme", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/messsysteme/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/neubau", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/neubau/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/reparaturen", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/reparaturen/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/sanierung", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/sanierung/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/sicherheitstechnik", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/sicherheitstechnik/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/smart-home", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/leistungen/elektrotechnik/smart-home/", destination: "/leistungen/elektrotechnik", permanent: true },
      // Projekte: reinigung + facility → reinigung-facility (konsolidiert)
      { source: "/projekte/reinigung", destination: "/projekte/reinigung-facility", permanent: true },
      { source: "/projekte/reinigung/", destination: "/projekte/reinigung-facility", permanent: true },
      { source: "/projekte/facility", destination: "/projekte/reinigung-facility", permanent: true },
      { source: "/projekte/facility/", destination: "/projekte/reinigung-facility", permanent: true },
      // /partner-werden entfernt → /kontakt
      { source: "/partner-werden", destination: "/kontakt", permanent: true },
      { source: "/partner-werden/", destination: "/kontakt", permanent: true },
      // Meisterleistungen → Projekte (Source of Truth)
      { source: "/meisterleistungen", destination: "/projekte", permanent: true },
      { source: "/meisterleistungen/", destination: "/projekte", permanent: true },
      { source: "/meisterleistungen/:slug", destination: "/projekte/:slug", permanent: true },
      // Legacy redirects (301) → /leistungen
      { source: "/handwerk", destination: "/leistungen", permanent: true },
      { source: "/handwerk/", destination: "/leistungen", permanent: true },
      { source: "/handwerk/elektrotechnik/elektro-notdienst", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/handwerk/elektrotechnik/elektro-notdienst/", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/handwerk/elektrotechnik", destination: "/leistungen/elektrotechnik", permanent: true },
      { source: "/handwerk/elektrotechnik/", destination: "/leistungen/elektrotechnik/", permanent: true },
      { source: "/handwerk/elektrotechnik/:path*", destination: "/leistungen/elektrotechnik/:path*", permanent: true },
      { source: "/handwerk/sanitaer-heizung", destination: "/leistungen/sanitaer-heizung", permanent: true },
      { source: "/handwerk/sanitaer-heizung/", destination: "/leistungen/sanitaer-heizung/", permanent: true },
      { source: "/handwerk/innenausbau", destination: "/leistungen/innenausbau", permanent: true },
      { source: "/handwerk/innenausbau/", destination: "/leistungen/innenausbau/", permanent: true },
      { source: "/handwerk/reinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/handwerk/reinigung/", destination: "/leistungen/reinigung-facility/reinigung/", permanent: true },
      { source: "/handwerk/facility", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/handwerk/facility/", destination: "/leistungen/reinigung-facility/facility/", permanent: true },
      { source: "/handwerk/service-wartung", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/handwerk/service-wartung/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/handwerk/reinigung-facility", destination: "/leistungen/reinigung-facility", permanent: true },
      { source: "/handwerk/reinigung-facility/", destination: "/leistungen/reinigung-facility/", permanent: true },
      { source: "/handwerk/:path*", destination: "/leistungen", permanent: true },
      // /reinigung Landing → Redirect auf /leistungen/reinigung-facility/reinigung
      { source: "/reinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/", destination: "/leistungen/reinigung-facility/reinigung/", permanent: true },
      // Reinigung Thin-Content: gelöschte Unterseiten → /leistungen/reinigung-facility/reinigung
      { source: "/leistungen/unterhaltsreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/unterhaltsreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/grundreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/grundreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/fensterreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/fensterreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/glas-fassade", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/glas-fassade/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/sonderreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/sonderreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/grauflaechenreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/grauflaechenreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/tiefgaragenreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/tiefgaragenreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/bueroreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/leistungen/bueroreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/unterhaltsreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/unterhaltsreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/grundreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/grundreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/fensterreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/fensterreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/glas-fassade", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/glas-fassade/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/sonderreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/sonderreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/grauflaechenreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/grauflaechenreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/tiefgaragenreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/tiefgaragenreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/bueroreinigung", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      { source: "/reinigung/bueroreinigung/", destination: "/leistungen/reinigung-facility/reinigung", permanent: true },
      // /facility-management → Redirect auf /leistungen/reinigung-facility/facility
      { source: "/facility-management", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/hausmeisterservice", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/hausmeisterservice/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/objektmanagement", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/objektmanagement/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/winterdienst", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/winterdienst/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/facility-management/:path*", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      // Facility & Außenanlagen Thin-Content: gelöschte Unterseiten → /leistungen/reinigung-facility/facility
      { source: "/leistungen/hausmeisterservice", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/hausmeisterservice/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/objektmanagement", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/objektmanagement/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/winterdienst", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/winterdienst/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/winterdienst-aussen", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/winterdienst-aussen/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/service-wartung", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/service-wartung/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/gruenpflege", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/gruenpflege/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/baumpflege", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      { source: "/leistungen/baumpflege/", destination: "/leistungen/reinigung-facility/facility", permanent: true },
      // /leistungen/innenausbau → eigene Seite (Design-Prototyp), kein Redirect
    ];
  },
};

export default nextConfig;
