/**
 * Offizielle 25 Münchner Stadtbezirke (verwaltungsrechtliche Gliederung).
 * Quelle: Stadt München, Wikipedia – Stadtbezirke Münchens.
 */
export const MUENCHEN_STADTTEILE = [
  "Allach-Untermenzing",
  "Altstadt-Lehel",
  "Aubing-Lochhausen-Langwied",
  "Au-Haidhausen",
  "Berg am Laim",
  "Bogenhausen",
  "Feldmoching-Hasenbergl",
  "Hadern",
  "Laim",
  "Ludwigsvorstadt-Isarvorstadt",
  "Maxvorstadt",
  "Milbertshofen-Am Hart",
  "Moosach",
  "Neuhausen-Nymphenburg",
  "Obergiesing-Fasangarten",
  "Pasing-Obermenzing",
  "Ramersdorf-Perlach",
  "Schwanthalerhöhe",
  "Schwabing-Freimann",
  "Schwabing-West",
  "Sendling",
  "Sendling-Westpark",
  "Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln",
  "Trudering-Riem",
  "Untergiesing-Harlaching",
] as const;

/**
 * Alle Gemeinden und Städte im Münchner Umland:
 * Landkreis München (29), Ebersberg (21), Dachau (17), Fürstenfeldbruck (23),
 * Freising (24), Starnberg (14). Alphabetisch sortiert.
 * Quelle: Wikipedia – Listen der Gemeinden der jeweiligen Landkreise.
 */
export const UMLAND_ORTE = [
  "Adelshofen",
  "Alling",
  "Allershausen",
  "Altomünster",
  "Althegnenberg",
  "Andechs",
  "Aschheim",
  "Aßling",
  "Attenkirchen",
  "Au in der Hallertau",
  "Aying",
  "Baierbrunn",
  "Baiern",
  "Berg",
  "Bergkirchen",
  "Brunnthal",
  "Bruck",
  "Dachau",
  "Ebersberg",
  "Egenhofen",
  "Egmating",
  "Eichenau",
  "Emmering",
  "Erdweg",
  "Fahrenzhausen",
  "Feldafing",
  "Feldkirchen",
  "Forstinning",
  "Frauenneuharting",
  "Freising",
  "Fürstenfeldbruck",
  "Gammelsdorf",
  "Garching bei München",
  "Gauting",
  "Germering",
  "Gilching",
  "Glonn",
  "Grafing bei München",
  "Grafrath",
  "Gräfelfing",
  "Grasbrunn",
  "Gröbenzell",
  "Grünwald",
  "Haag an der Amper",
  "Haar",
  "Haimhausen",
  "Hallbergmoos",
  "Hattenhofen",
  "Hebertshausen",
  "Herrsching am Ammersee",
  "Hilgertshausen-Tandern",
  "Hohenbrunn",
  "Hohenkammer",
  "Hohenlinden",
  "Höhenkirchen-Siegertsbrunn",
  "Hörgertshausen",
  "Inning am Ammersee",
  "Ismaning",
  "Jesenwang",
  "Karlsfeld",
  "Kirchdorf an der Amper",
  "Kirchheim bei München",
  "Kirchseeon",
  "Kottgeisering",
  "Krailling",
  "Kranzberg",
  "Landsberied",
  "Langenbach",
  "Maisach",
  "Mammendorf",
  "Markt Indersdorf",
  "Markt Schwaben",
  "Marzling",
  "Mauern",
  "Mittelstetten",
  "Moorenweis",
  "Moosach",
  "Moosburg an der Isar",
  "Nandlstadt",
  "Neubiberg",
  "Neufahrn bei Freising",
  "Neuried",
  "Oberhaching",
  "Oberschleißheim",
  "Oberschweinbach",
  "Oberpframmern",
  "Odelzhausen",
  "Olching",
  "Ottobrunn",
  "Paunzhausen",
  "Petershausen",
  "Pfaffenhofen a.d.Glonn",
  "Planegg",
  "Pliening",
  "Pöcking",
  "Poing",
  "Puchheim",
  "Pullach im Isartal",
  "Putzbrunn",
  "Röhrmoos",
  "Rudelzhausen",
  "Sauerlach",
  "Schäftlarn",
  "Schöngeising",
  "Schwabhausen",
  "Seefeld",
  "Starnberg",
  "Steinhöring",
  "Straßlach-Dingharting",
  "Sulzemoos",
  "Taufkirchen",
  "Tutzing",
  "Türkenfeld",
  "Unterföhring",
  "Unterhaching",
  "Unterschleißheim",
  "Vaterstetten",
  "Vierkirchen",
  "Wang",
  "Weichs",
  "Weßling",
  "Wolfersdorf",
  "Wörthsee",
  "Zolling",
  "Zorneding",
] as const;

export type MuenchenStadtteil = (typeof MUENCHEN_STADTTEILE)[number];
export type UmlandOrt = (typeof UMLAND_ORTE)[number];
